version: '3.8'

services:
  insightplatform.api:
    image: ${DOCKER_REGISTRY-}insightplatformapi
    build:
      context: .
      dockerfile: InsightPlatform.Api/Dockerfile
    volumes:
      - ./InsightPlatform.Api/appsettings.Production.json:/app/appsettings.Production.json:ro
      - /home/sixgo_admin/deploy-insight-api/socket:/app/socket
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://unix:/app/socket.sock
    restart: always
