version: '3.8'

services:
  insightplatform.api:
    user: root
    image: ${DOCKER_REGISTRY-}insightplatformapi
    build:
      context: .
      dockerfile: InsightPlatform.Api/Dockerfile
    volumes:
      - ./InsightPlatform.Api/appsettings.Production.json:/app/appsettings.Production.json:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "${INSIGHT_API_PORT:-6500}:6500"  # dùng port động theo ENV
    command: ["dotnet", "InsightPlatform.Api.dll", "--urls", "http://0.0.0.0:6500"]
    restart: always
