version: '3.8'

services:
  insightplatform.api:
    user: root
    image: ${DOCKER_REGISTRY-}insightplatformapi
    build:
      context: .
      dockerfile: InsightPlatform.Api/Dockerfile
    volumes:
      - ./InsightPlatform.Api/appsettings.Production.json:/app/appsettings.Production.json:ro
      - ./socket:/app/socket
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    command: >
      bash -c "dotnet InsightPlatform.Api.dll --urls http://unix:/app/socket/socket.sock"
    restart: always
