version: '3.8'

services:
  insightplatform.api:
    image: ${DOCKER_REGISTRY-}insightplatformapi
    build:
      context: .
      dockerfile: InsightPlatform.Api/Dockerfile
    ports:
      - "5000:8080"
    volumes:
      - ./InsightPlatform.Api/appsettings.Production.json:/app/appsettings.Production.json:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
